"use client";

import { redirect } from "next/navigation";
import { useState, useMemo } from "react";
import { Sidebar } from "~/components/dashboard/Sidebar";
import { 
  Target, 
  FileText, 
  BarChart3, 
  Globe, 
  ArrowRight, 
  Lock, 
  Inbox, 
  ExternalLink,
  Search,
  Filter,
  Clock,
  ChevronRight
} from "lucide-react";

const TIER_ORDER: Record<string, number> = { All: 0, Explorer: 1, Visionary: 2, Trailblazer: 3 };
const TIER_RANK: Record<string, number> = { Explorer: 1, Visionary: 2, Trailblazer: 3 };

const TYPE_ICON: Record<string, any> = {
  "Market Report": Globe,
  "Intelligence": Target,
  "R&D": BarChart3,
  "Strategy": FileText,
};

const TIER_BADGE: Record<string, string> = {
  All:         "bg-zinc-100 text-zinc-600 border-zinc-200 dark:bg-zinc-800 dark:text-zinc-400 dark:border-zinc-700",
  Explorer:    "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-500/10 dark:text-blue-400 dark:border-blue-500/20",
  Visionary:   "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-500/10 dark:text-amber-400 dark:border-amber-500/20",
  Trailblazer: "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-500/10 dark:text-purple-400 dark:border-purple-500/20",
};

export default function InsightsPage({ 
  profile, 
  insights: allInsights 
}: { 
  profile: { id: string; tier: string | null }; 
  insights: Array<{
    id: string;
    title: string;
    type: string;
    summary: string | null;
    readTime: string | null;
    date: string;
    contentUrl: string | null;
    tierRequired: string;
  }> 
}) {
  const [search, setSearch] = useState("");
  const [activeFilter, setActiveFilter] = useState("All");

  const userTierRank = TIER_RANK[profile.tier ?? "Explorer"] ?? 1;

  const filtered = useMemo(() => {
    return allInsights.filter(r => {
      const matchesSearch = r.title.toLowerCase().includes(search.toLowerCase()) || 
                            r.type.toLowerCase().includes(search.toLowerCase()) ||
                            r.summary?.toLowerCase().includes(search.toLowerCase());
      const matchesFilter = activeFilter === "All" || r.type === activeFilter;
      return matchesSearch && matchesFilter;
    });
  }, [allInsights, search, activeFilter]);

  const accessible = filtered.filter(r => (TIER_ORDER[r.tierRequired] ?? 0) <= userTierRank);
  const locked = filtered.filter(r => (TIER_ORDER[r.tierRequired] ?? 0) > userTierRank);

  const types = ["All", ...Array.from(new Set(allInsights.map(r => r.type)))];

  return (
    <div className="flex h-screen w-full overflow-hidden bg-zinc-50 dark:bg-zinc-950">
      <Sidebar profile={profile} />
      <div className="flex flex-1 flex-col min-w-0 min-h-0 overflow-hidden">
        {/* Top bar */}
        <div className="flex h-14 shrink-0 items-center justify-between px-8 border-b border-zinc-200/80 dark:border-zinc-800/80 bg-white dark:bg-zinc-950">
          <div className="flex items-center gap-3">
            <div className="h-7 w-7 rounded-lg bg-amber-50 dark:bg-amber-400/10 border border-amber-200/60 dark:border-amber-400/20 flex items-center justify-center">
              <Target className="w-3.5 h-3.5 text-amber-500 dark:text-amber-400" />
            </div>
            <div>
              <p className="text-xs font-bold text-zinc-800 dark:text-zinc-200">Intelligence Matrix</p>
              <p className="text-[10px] text-zinc-400 dark:text-zinc-500 uppercase tracking-widest">Proprietary R&D</p>
            </div>
          </div>

          <div className="flex items-center gap-4">
             <div className="relative group">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-zinc-400 group-focus-within:text-amber-500 transition-colors" />
                <input 
                  type="text" 
                  placeholder="Search intelligence..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  className="bg-zinc-100 dark:bg-zinc-900 border-none rounded-full px-9 py-1.5 text-[11px] focus:ring-1 focus:ring-amber-500/30 w-64 outline-none transition-all"
                />
             </div>
          </div>
        </div>

        <main className="flex-1 overflow-y-auto min-h-0">
          <div className="px-8 py-8 max-w-6xl mx-auto space-y-10">
            
            {/* Header section with Filters */}
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
               <div>
                  <h1 className="font-heading text-3xl tracking-tight text-zinc-800 dark:text-zinc-200 mb-2">Strategic Intelligence</h1>
                  <p className="text-sm text-zinc-500 dark:text-zinc-400 max-w-xl">
                    Deep market frameworks and proprietary R&D reports generated by the TIC internal research team.
                  </p>
               </div>
               
               <div className="flex items-center gap-2 overflow-x-auto pb-1 no-scrollbar">
                  {types.map(type => (
                    <button 
                      key={type}
                      onClick={() => setActiveFilter(type)}
                      className={`px-4 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-widest border transition-all whitespace-nowrap ${
                        activeFilter === type 
                        ? "bg-zinc-900 text-white border-zinc-900 dark:bg-white dark:text-zinc-900 dark:border-white" 
                        : "bg-white dark:bg-zinc-950 text-zinc-400 border-zinc-200 dark:border-zinc-800 hover:border-zinc-400 dark:hover:border-zinc-600"
                      }`}
                    >
                      {type}
                    </button>
                  ))}
               </div>
            </div>

            {/* Content Grid */}
            <div className="grid grid-cols-1 gap-6">
              {accessible.length === 0 && locked.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-24 gap-4 text-center bg-white dark:bg-zinc-900/40 rounded-3xl border border-dashed border-zinc-200 dark:border-zinc-800">
                  <Inbox className="w-8 h-8 text-zinc-300 dark:text-zinc-700" />
                  <div>
                    <p className="font-bold text-zinc-700 dark:text-zinc-300">No intelligence found</p>
                    <p className="text-xs text-zinc-400 dark:text-zinc-500">Try adjusting your filters or search query.</p>
                  </div>
                </div>
              ) : (
                <>
                  {/* Accessible Reports */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                    {accessible.map((report) => {
                      const Icon = TYPE_ICON[report.type] ?? BarChart3;
                      return (
                        <div key={report.id} className="group relative flex flex-col bg-white dark:bg-zinc-900/60 border border-zinc-200/80 dark:border-zinc-800/80 rounded-2xl p-6 hover:border-amber-500/30 dark:hover:border-amber-400/20 transition-all duration-300 shadow-sm">
                          <div className="flex items-start justify-between mb-4">
                            <div className="h-10 w-10 rounded-xl bg-zinc-50 dark:bg-zinc-800 border border-zinc-100 dark:border-zinc-700 flex items-center justify-center shrink-0 group-hover:scale-110 transition-transform duration-500">
                              <Icon className="w-4 h-4 text-zinc-400 dark:text-zinc-500 group-hover:text-amber-500 dark:group-hover:text-amber-400" />
                            </div>
                            <div className="flex flex-col items-end gap-1.5">
                              <span className={`text-[8px] font-bold uppercase tracking-[0.15em] px-2 py-0.5 rounded-full border ${TIER_BADGE[report.tierRequired] ?? ""}`}>
                                {report.tierRequired}
                              </span>
                              {report.readTime && (
                                <span className="flex items-center gap-1 text-[8px] uppercase tracking-widest text-zinc-400">
                                  <Clock className="w-2.5 h-2.5" /> {report.readTime}
                                </span>
                              )}
                            </div>
                          </div>

                          <div className="mb-6">
                            <span className="text-[9px] font-bold uppercase tracking-[0.2em] text-amber-600/80 dark:text-amber-400/80 mb-1.5 block">{report.type}</span>
                            <h3 className="font-heading text-xl text-zinc-800 dark:text-zinc-100 leading-tight mb-2 group-hover:text-amber-600 dark:group-hover:text-amber-400 transition-colors">{report.title}</h3>
                            <p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed line-clamp-3">
                              {report.summary ?? "Access proprietary intelligence and frameworks developed specifically for TIC founders."}
                            </p>
                          </div>

                          <div className="mt-auto pt-6 border-t border-zinc-100 dark:border-zinc-800/50 flex items-center justify-between">
                            <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">{report.date}</p>
                            {report.contentUrl ? (
                              <a href={report.contentUrl} target="_blank" rel="noopener noreferrer" 
                                 className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-zinc-600 dark:text-zinc-300 hover:text-amber-500 transition-colors">
                                Open Intelligence <ExternalLink className="w-3 h-3" />
                              </a>
                            ) : (
                              <button className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-zinc-600 dark:text-zinc-300 hover:text-amber-500 transition-colors">
                                View Report <ChevronRight className="w-3 h-3" />
                              </button>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Locked Reports */}
                  {locked.length > 0 && (
                    <div className="space-y-4 pt-8">
                       <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-zinc-400 dark:text-zinc-500">Premium Intelligence (Locked)</p>
                       <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                          {locked.map(report => (
                            <div key={report.id} className="group relative bg-zinc-100/50 dark:bg-zinc-900/30 border border-dashed border-zinc-200 dark:border-zinc-800 p-5 rounded-2xl opacity-60 grayscale hover:grayscale-0 transition-all">
                               <div className="flex items-center justify-between mb-4">
                                  <div className="h-8 w-8 rounded-lg bg-zinc-200 dark:bg-zinc-800 flex items-center justify-center">
                                     <Lock className="w-3.5 h-3.5 text-zinc-400 dark:text-zinc-600" />
                                  </div>
                                  <span className={`text-[7px] font-bold uppercase tracking-widest px-2 py-0.5 rounded-full border ${TIER_BADGE[report.tierRequired]}`}>
                                    {report.tierRequired} ONLY
                                  </span>
                               </div>
                               <h4 className="font-heading text-sm text-zinc-600 dark:text-zinc-400 mb-1">{report.title}</h4>
                               <p className="text-[8px] uppercase tracking-widest text-zinc-400">{report.type} · {report.date}</p>
                            </div>
                          ))}
                       </div>
                    </div>
                  )}
                </>
              )}
            </div>

            {/* Bespoke request CTA */}
            <div className="relative overflow-hidden bg-zinc-900 dark:bg-white rounded-3xl p-10 text-center">
              {/* Background pattern */}
              <div className="absolute inset-0 opacity-10 pointer-events-none" 
                   style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '32px 32px' }} />
              
              <div className="relative z-10 max-w-2xl mx-auto">
                <h3 className="font-heading text-3xl text-white dark:text-zinc-900 mb-4">Request Bespoke Research</h3>
                <p className="text-zinc-400 dark:text-zinc-500 mb-8 leading-relaxed">
                  Need deep intelligence on a specific niche, competitor, or technology stack? Our internal R&D team provides custom intelligence reports for Visionary and Trailblazer members.
                </p>
                <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                  <button className="px-8 py-3 bg-amber-500 hover:bg-amber-600 text-zinc-900 text-[11px] font-bold uppercase tracking-widest transition-all">
                    Initialize Request
                  </button>
                  <p className="text-[10px] text-zinc-500 font-medium italic">Available for higher tiers</p>
                </div>
              </div>
            </div>

          </div>
        </main>
      </div>
    </div>
  );
}
